### PR TITLE
Recognize a complete url as a token, this includes various url forms ...

### LINKED ISSUE #4: URLs tokenzing individual characters in the URL
`Tokenizer::WhitespaceTokenizer.new.tokenize "www.google.com"`
`  => ["www", ".", "g","o","o","g","l","e",".","c","o","m"]`

I want the website urls to be tokenized as a single noun effectively so would expect www.google.com to tokenize as "www.google.com". I am happy to fork this repo and would like to contribute. 

Thanks for repo btw, it's useful.

### PR DESCRIPTION
**Pull request by joshweir**
Recognize a complete url as a token, this includes various url forms eg. https://www.google.com, google.com, etc

Fixes #4

Anything else you need me to clean up in this please let me know.

### CODE REVIEW

**Comment by arbox** [comment]
@joshweir thank you for this PR, I'll review this on Wednesday in next week. Please be patient :)

**Comment by joshweir** [comment]
@arbox No rush. If there are any issues, more than happy to take feedback and rework.

**Comment by arbox** [comment]
@joshweir ok, that's time to look at your work, very excited :)

**Comment by Nakilon** [comment]
What's up?
Also there is this thing: https://stackoverflow.com/a/4716605/322020

**Pull request closed without merging**
